/* Public browser keys are returned by /api/config; server credentials never enter this file. */
const API_BASE = "https://yoxi-city-rhythm-api.1qaz0726.workers.dev";
const FALLBACK = {lat:25.0569,lng:121.5104};
const $ = (s) => document.querySelector(s);
const escapeHtml = (v) => String(v ?? "").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const stages = [
 {title:"這一刻，想做什麼？",helper:"選現在想完成的一件小事就好。",values:["吃點東西","喝杯咖啡","走走看看","坐著休息","找洗手間","找室內待著"]},
 {title:"用自己的步調。",helper:"少走一點，或多看看一點，都可以。",values:["快速完成","慢慢走","少走一點","可多走一點","只去一站","想去兩三站"]},
 {title:"再加一點你的感覺。",helper:"這是偏好，不保證現場安靜、人少或有座位。",values:["安靜","在地","有點驚喜","有綠意","有文化感","簡單穩妥"]}
];
const state={screen:"discover",stage:0,selected:0,choices:[],minutes:45,returnToOrigin:false,entry:"self",location:null,fallback:false,places:[],route:null,excluded:[],journey:null,error:"",feedback:null};
let map,mapProvider,mapReady=false,markers=[],lines=[],controller,requestVersion=0,toastTimer;
function readStore(key,fallback){try{const value=JSON.parse(localStorage.getItem(key));if(value===null)return fallback;if(key==="yoxi.events")return Array.isArray(value)?value.filter(v=>v&&typeof v.event==="string").slice(-500):[];if(key==="yoxi.preference")return Array.isArray(value.choices)&&value.choices.length===3&&value.choices.every((v,i)=>stages[i].values.includes(v))?value:fallback;return value;}catch{return fallback;}}
function saveStore(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{return false;}}
function track(event,extra={}){const events=readStore("yoxi.events",[]);saveStore("yoxi.events",[...events,{event,at:new Date().toISOString(),entry:state.entry,...extra}].slice(-500));}
function toast(message){clearTimeout(toastTimer);$("#toast").textContent=message;$("#toast").classList.add("visible");toastTimer=setTimeout(()=>$("#toast").classList.remove("visible"),4500);}
function show(content){$("#screen").innerHTML='<div class="fade-in">'+content+'</div>';$("#screen").scrollTop=0;$("#screen").focus({preventScroll:true});collapse(false);}
function collapse(value){$("#app").classList.toggle("collapsed",value);$("#sheet-toggle").setAttribute("aria-expanded",String(!value));$("#sheet-toggle").setAttribute("aria-label",value?"展開帶路面板":"收合面板，查看地圖");$("#sheet-toggle small").textContent=value?"繼續帶路":"查看地圖";$("#screen").inert=value;if(mapReady)setTimeout(()=>{if(mapProvider==="geoapify")map.resize();else google.maps.event.trigger(map,"resize");fitMap();},370);}
function heading(kicker,title){return '<div class="heading"><div><p class="kicker">'+kicker+'</p><h2>'+escapeHtml(title)+'</h2></div><img src="assets/yoxi-app-icon.png" alt="yoxi"></div>';}
function chips(){return '<div class="chips">'+state.choices.map((v,i)=>'<button class="chip" data-edit="'+i+'">'+escapeHtml(v)+' ↗</button>').join("")+'</div>';}
function bindChips(){document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>{state.stage=Number(b.dataset.edit);renderDiscover();});}
function renderDiscover(){
 state.screen="discover";const stage=stages[state.stage];state.selected=Math.max(0,stage.values.indexOf(state.choices[state.stage]));
 const memory=readStore("yoxi.preference",null);
 const welcome=state.stage===0&&memory?.choices?.length===3?'<div class="memory"><strong>還記得你上次的步調。</strong><p>'+memory.choices.map(escapeHtml).join(" · ")+'</p><button class="secondary" id="reuse">沿用上次偏好，直接選時間 →</button></div>':"";
 show('<div class="segmented"><button data-entry="ride" class="'+(state.entry==="ride"?"selected":"")+'">搭 yoxi 抵達</button><button data-entry="self" class="'+(state.entry==="self"?"selected":"")+'">我自己來的</button></div>'+welcome+heading("A MOMENT FOR YOU",stage.title)+'<p class="sub">'+stage.helper+'</p><div class="progress">'+[0,1,2,3].map(i=>'<i class="'+(i<=state.stage?"active":"")+'"></i>').join("")+'</div><div class="step-label"><span>'+["目的","步調","感受"][state.stage]+'</span><span>'+ (state.stage+1)+' / 4</span></div><div class="wheel">'+stage.values.map((v,i)=>'<button class="wheel-option '+(i===state.selected?"selected":"")+'" style="--i:'+i+'" data-choice="'+i+'" aria-pressed="'+(i===state.selected)+'">'+v+'</button>').join("")+'<button class="wheel-center" id="confirm-choice"><small>現在想要</small><strong id="choice-label">'+stage.values[state.selected]+'</strong><span>確認，繼續 →</span></button></div><button class="primary" id="choice-next">就選這個，下一步 →</button>'+(state.stage?'<button class="text-button" id="previous-step">← 上一步</button>':'<p class="fine">不需要行事曆，也不必輸入下一站。'+(state.entry==="ride"?"此入口為情境展示，未讀取乘車紀錄。":"")+'</p>'));
 if(state.stage>0)$(".segmented").hidden=true;
 document.querySelectorAll("[data-choice]").forEach(b=>b.onclick=()=>{state.selected=Number(b.dataset.choice);document.querySelectorAll("[data-choice]").forEach(n=>{const active=n===b;n.classList.toggle("selected",active);n.setAttribute("aria-pressed",String(active));});$("#choice-label").textContent=stage.values[state.selected];});
 const next=()=>{state.choices[state.stage]=stage.values[state.selected];track("preference_selected",{stage:state.stage,value:stage.values[state.selected]});state.stage++;state.stage<3?renderDiscover():renderTime();};
 $("#choice-next").onclick=next;$("#confirm-choice").onclick=next;
 if($("#previous-step"))$("#previous-step").onclick=()=>{state.stage--;renderDiscover();};
 document.querySelectorAll("[data-entry]").forEach(b=>b.onclick=()=>{state.entry=b.dataset.entry;track(state.entry==="ride"?"entry_ride_arrival":"entry_nonride");renderDiscover();});
 if($("#reuse"))$("#reuse").onclick=()=>{state.choices=memory.choices.slice(0,3);state.minutes=Number(memory.minutes)||45;state.returnToOrigin=Boolean(memory.returnToOrigin);track("preference_reused");renderTime();};
}
function renderTime(){
 state.screen="time";
 show(heading("ONE LAST THING","這段空檔，有多久？")+chips()+'<p class="sub">不必排滿。步行、停留之外，也會留點緩衝。</p><div class="time-hero"><div class="time-number"><span id="minutes-value">'+state.minutes+'</span><small>分鐘</small></div><input id="time-range" aria-label="可用時間，分鐘" type="range" min="15" max="120" step="5" value="'+state.minutes+'"><div class="range-labels"><span>15 分</span><span>60 分</span><span>120 分</span></div></div><div class="presets">'+[25,45,75,105].map(n=>'<button data-minutes="'+n+'" class="'+(n===state.minutes?"selected":"")+'">'+n+' 分</button>').join("")+'</div><label class="return-choice"><input id="return-origin" type="checkbox" '+(state.returnToOrigin?"checked":"")+'>結束時，要走回出發點</label>'+(!state.location?'<div class="error-box">還沒有位置。請使用定位，或明確選擇大稻埕體驗。</div><div class="row"><button class="secondary" id="locate-now">使用我的位置</button><button class="secondary" id="demo-location">大稻埕體驗</button></div>':'<p class="fine">出發點：'+(state.fallback?"大稻埕（你選擇的體驗位置）":"裝置定位")+'。'+(state.returnToOrigin?"會將回程步行計入預算。":"在最後一站結束，不包含前往下一個行程。")+'</p>')+(state.error?'<div class="error-box" role="alert">'+escapeHtml(state.error)+'</div>':"")+'<button class="primary" id="build-route" '+(!state.location?"disabled":"")+'>幫我安排這段空檔 →</button><button class="text-button" id="time-back">← 回到感受選擇</button>');
 bindChips();const setTime=n=>{state.minutes=Math.max(15,Math.min(120,Number(n)));$("#minutes-value").textContent=state.minutes;$("#time-range").value=state.minutes;document.querySelectorAll("[data-minutes]").forEach(b=>b.classList.toggle("selected",Number(b.dataset.minutes)===state.minutes));};
 $("#time-range").oninput=e=>setTime(e.target.value);document.querySelectorAll("[data-minutes]").forEach(b=>b.onclick=()=>setTime(b.dataset.minutes));
 $("#return-origin").onchange=e=>{state.returnToOrigin=e.target.checked;renderTime();};$("#build-route").onclick=()=>generatePlan();$("#time-back").onclick=()=>{state.stage=2;renderDiscover();};
 if($("#locate-now"))$("#locate-now").onclick=requestLocation;if($("#demo-location"))$("#demo-location").onclick=()=>setLocation(FALLBACK,true);
}
function setLocation(location,fallback){state.location=location;state.fallback=fallback;$("#location-label").textContent=fallback?"大稻埕・體驗位置":"目前位置・裝置定位";updateMap();if(state.screen==="time")renderTime();}
let locationVersion=0;
function requestLocation(){
 const active=()=>state.screen==="loading"||(state.journey&&!["done","early","partial"].includes(state.journey.status));
 if(active())return toast("規劃或帶路中會保留出發點；結束後再重新定位。");
 if(!navigator.geolocation)return toast("裝置不支援定位，可在時間步驟選擇大稻埕體驗。");
 const version=++locationVersion;const originalLocation=state.location;
 $("#location-label").textContent="正在取得定位…";
 navigator.geolocation.getCurrentPosition(({coords})=>{
  if(version!==locationVersion||active()||state.location!==originalLocation)return;
  state.route=null;state.places=[];setLocation({lat:coords.latitude,lng:coords.longitude},false);
  if(state.screen==="route"){state.error="位置已更新，請重新規劃。";renderTime();}
 },()=>{
  if(version!==locationVersion||active()||state.location!==originalLocation)return;
  $("#location-label").textContent=state.location?(state.fallback?"大稻埕・體驗位置":"保留上次定位"):"定位未授權";
  toast("無法取得定位；你可允許位置權限，或在最後一步選大稻埕體驗。");
  if(state.screen==="time")renderTime();
 },{enableHighAccuracy:true,timeout:10000,maximumAge:120000});
}
async function requestJson(url,options={}){const response=await fetch(url,{...options,headers:{"Content-Type":"application/json",...options.headers}});let data;try{data=await response.json();}catch{throw new Error("服務回應格式異常，請稍後再試。");}if(!response.ok){const error=new Error(data.message||"服務暫時無法回應。");error.code=data.error;throw error;}return data;}
function planError(error){const messages={no_reachable_places:"這一帶沒有找到符合條件、可步行到達的地點。試試其他目的，或換個街區。",no_feasible_plan:"這段時間不夠完成符合條件的路線。可以增加時間或改成只去一站。",places_unavailable:"地點資料服務暫時沒有回應。選擇都還在，可以再試一次。",service_not_configured:"地圖資料服務尚未完成金鑰設定。請聯絡原型管理者。",map_not_configured:"地圖金鑰尚未設定完成。",google_request_failed:"Google 地圖服務暫時無法回應，請稍後再試。"};return messages[error.code]|| (error.name==="TypeError"?"目前無法連上服務，請確認網路後重試。":error.message);}
async function generatePlan(replace=false){
 if(!state.location)return renderTime();if(replace)state.excluded=[...new Set([...state.excluded,...state.places.map(p=>p.id)])].slice(-30);
 const version=++requestVersion;controller?.abort();controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),45000);state.screen="loading";state.error="";
 show('<div class="thinking"><div class="orb"><img src="assets/yoxi-app-icon.png" alt=""></div><p class="kicker">FINDING YOUR LITTLE MOMENT</p><h2>把這段時間，安排剛好。</h2><p class="sub">正在查找真實地點、挑選方案，並計算步行與停留時間。<br>如果走不完，就不會勉強安排。</p><p class="fine">處理中・不是即時進度百分比</p><button class="text-button" id="cancel-plan">取消，回到我的選擇</button></div>');
 $("#cancel-plan").onclick=()=>{requestVersion++;controller.abort();renderTime();};
 try{const data=await requestJson(API_BASE+"/api/plan",{method:"POST",signal:controller.signal,body:JSON.stringify({origin:state.location,arrivalMode:state.entry,preferences:{purpose:state.choices[0],rhythm:state.choices[1],feeling:state.choices[2]},timeMinutes:state.minutes,returnToOrigin:state.returnToOrigin,excludePlaceIds:state.excluded})});if(version!==requestVersion)return;
 if(!data.places?.length||!data.route?.geometry)throw new Error("沒有收到完整地點與步行路線，請再試一次。");
 state.places=data.places;state.route=data.route;state.plan=data.plan;state.planner=data.planner;state.provenance=data.provenance;state.journey=null;state.feedback=null;track("plan_generated",{planner:data.planner,stops:data.places.length,minutes:state.minutes});renderPlan();updateMap();
 }catch(error){if(version!==requestVersion)return;state.error=error.name==="AbortError"?"規劃花的時間比較久，已停止等待。你的選擇還在，請重試。":planError(error);track("plan_failed",{code:error.code||"request_failed"});renderTime();}finally{clearTimeout(timeout);}
}
function budget(){const r=state.route;const walk=Number(r.walkMinutes??r.walkingMinutes??Math.ceil(Number(r.totalDurationSeconds||r.durationSeconds||0)/60));const stay=Number(r.stayMinutes??r.totalStayMinutes??state.places.reduce((n,p)=>n+Number(p.suggestedStayMinutes||0),0));const buffer=Number(r.bufferMinutes||0);const free=Number(r.freeMinutes??Math.max(0,state.minutes-walk-stay-buffer));return{walk,stay,buffer,free};}
function placeCard(place,index){
 const open=place.openingStatus==="open"?"查詢時營業中，抵達前請再確認":place.openingStatus==="closed"?"目前標示休息":"營業時間待確認";
 const credits=(Array.isArray(place.attributions)?place.attributions:[]).map(a=>{let url;try{const parsed=new URL(a.providerUri);if(parsed.protocol==="https:")url=parsed.href;}catch{}return url?'<a target="_blank" rel="noopener noreferrer" href="'+escapeHtml(url)+'">'+escapeHtml(a.provider||"資料提供者")+'</a>':escapeHtml(a.provider||"");}).filter(Boolean).join(" · ");
 return '<article class="stop"><div class="stop-header"><span class="stop-number">'+(index+1)+'</span><div><h3>'+escapeHtml(place.name)+'</h3><p>'+escapeHtml(place.address||"地址資料未提供")+'</p></div></div><div class="stop-meta"><span>原方案步行約 '+Math.max(1,Math.ceil(Number(place.legDurationSeconds||0)/60))+' 分</span><span>建議停留 '+Number(place.suggestedStayMinutes||0)+' 分</span></div><p>'+open+'</p><p>地點資料：'+escapeHtml(place.source||place.provider||"地圖供應商")+(credits?" · "+credits:"")+'</p><a href="'+placeLink(place)+'" target="_blank" rel="noopener noreferrer">在 Google Maps 確認地點 ↗</a></article>';
}
function placeLink(place){return "https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(place.name+" "+place.location.latitude+","+place.location.longitude);}
function navigationLink(place){return "https://www.google.com/maps/dir/?api=1&destination="+encodeURIComponent(place.location.latitude+","+place.location.longitude)+"&travelmode=walking";}
function renderPlan(){state.screen="route";const b=budget();show(heading("A LITTLE PLAN, JUST FOR YOU","這樣過，剛剛好。")+chips()+'<p class="sub">'+escapeHtml(state.plan?.intro||"先完成最想做的一件事，再把剩下的時間留給自己。")+'</p><div class="budget">'+[[b.walk,"步行"],[b.stay,"停留"],[b.buffer,"緩衝"],[b.free,"彈性剩餘"]].map(([n,t])=>'<div><b>'+n+'<em>分</em></b><small>'+t+'</small></div>').join("")+'</div><p class="fine">'+state.minutes+' 分鐘預算・'+(state.route.returnToOrigin?"已包含步行回出發點":"最後一站結束，不含下一個行程")+'。彈性時間不用填滿。</p>'+state.places.map(placeCard).join("")+'<button class="primary" id="start-plan">開始這段空檔 →</button><div class="row"><button class="secondary" id="replace-plan">換個推薦</button><button class="secondary" id="edit-time">調整時間</button></div><details class="trust"><summary>為什麼推薦？哪些可以確認？</summary><p>依你的「'+state.choices.map(escapeHtml).join(" · ")+'」挑選。安靜、氣氛與現場人潮只是偏好，沒有足夠資料時不保證。</p><ul><li>地點來源：'+escapeHtml(state.places[0].source||state.places[0].provider||"地圖供應商")+'</li><li>步行：路線服務估算；停留與緩衝：規則計算，非保證到達時間。</li><li>排序：'+(state.planner==="openrouter"?"AI 從真實候選中挑選，再由規則驗算。":"AI 未啟用或不可用，改以規則排序。")+'</li><li>yoxi 聚合訊號：尚未接入，不冒充個人乘車紀錄。</li></ul></details>');bindChips();$("#start-plan").onclick=startJourney;$("#replace-plan").onclick=()=>generatePlan(true);$("#edit-time").onclick=renderTime;}
function startJourney(){state.journey={index:0,status:"walking",startedAt:Date.now(),arrivedAt:null,completed:0,skipped:0};track("plan_started");renderJourney();}
function renderJourney(){state.screen="journey";const j=state.journey;const p=state.places[j.index];const elapsed=Math.floor((Date.now()-j.startedAt)/60000);const left=Math.max(0,state.minutes-elapsed);const staying=j.status==="staying";const returning=j.status==="returning";const dest=returning?{name:"出發點",location:{latitude:state.location.lat,longitude:state.location.lng}}:p;
 show('<p class="kicker">'+(returning?"BACK TO YOUR START":"YOUR LITTLE MOMENT")+'</p><h2>'+(returning?"慢慢走回出發點。":staying?"到了，就停留一下。":"接下來，去這裡。")+'</h2><p class="status-line">'+(returning?"回程":(j.index+1)+" / "+state.places.length+" 站")+'・空檔還有約 '+left+' 分鐘</p>'+(elapsed>=state.minutes?'<div class="error-box">原本的時間預算已用完。請確認下一段安排，必要時提早結束。</div>':"")+(returning?'<h3>回到這次的出發點</h3><p class="sub">回程已計入原始方案；實際步行與停留仍可能不同。</p>':placeCard(p,j.index))+(staying?'<div class="journey-time">'+p.suggestedStayMinutes+' <small>分左右</small></div><p class="sub">這是建議停留，不是倒數壓力。想走了就繼續。</p>':'<a class="primary" id="open-nav" href="'+navigationLink(dest)+'" target="_blank" rel="noopener noreferrer">開啟 Google Maps 步行導航 ↗</a><p class="fine">導航在另一個分頁開啟；回來後，請自己確認抵達。</p>')+'<button class="'+(staying?"primary":"secondary")+'" id="journey-next">'+(returning?"我已回到出發點":staying?"完成這一站 →":"我到了")+'</button>'+(!returning?'<button class="text-button" id="skip-place">這站不適合，跳過</button>':"")+'<button class="text-button" id="finish-early">提早結束這段空檔</button>');
 if($("#open-nav"))$("#open-nav").onclick=()=>track("navigation_opened",{stop:j.index,returning});
 $("#journey-next").onclick=()=>{if(returning)return finishJourney(false);if(!staying){j.status="staying";j.arrivedAt=Date.now();track("place_arrived",{stop:j.index});renderJourney();}else{j.completed++;track("place_completed",{stop:j.index,stayMinutes:Math.floor((Date.now()-j.arrivedAt)/60000)});advanceJourney();}};
 if($("#skip-place"))$("#skip-place").onclick=()=>{j.skipped++;track("place_skipped",{stop:j.index});advanceJourney();};
 $("#finish-early").onclick=()=>finishJourney(true);
}
function advanceJourney(){const j=state.journey;if(j.index<state.places.length-1){j.index++;j.status="walking";j.arrivedAt=null;renderJourney();}else if(state.route.returnToOrigin){j.status="returning";renderJourney();}else finishJourney(false);}
function finishJourney(early){const complete=!early&&state.journey.completed===state.places.length;state.journey.status=early?"early":complete?"done":"partial";track(early?"plan_ended_early":complete?"plan_completed":"plan_ended_partial",{completed:state.journey.completed,skipped:state.journey.skipped});saveStore("yoxi.preference",{choices:state.choices,minutes:state.minutes,returnToOrigin:state.returnToOrigin});renderFinished();}
function renderFinished(){state.screen="finished";const j=state.journey;show('<div class="journey-mark">✓</div><p class="kicker">A MOMENT, WELL SPENT</p><h2>'+(j.status==="early"?"就到這裡，也很好。":"把這段時間，留給了自己。")+'</h2><p class="sub">你確認完成了 '+j.completed+' 站'+(j.skipped?"，跳過 "+j.skipped+" 站":"")+'。下次不用從頭選，這台裝置會記得你的設定。</p><h3>這次的推薦，合你的意嗎？</h3>'+(state.feedback?'<p class="status-line">已記錄：'+(state.feedback==="like"?"喜歡":"不太適合")+'。不會把完成次數當成喜好。</p>':'<div class="row"><button class="secondary" id="like">喜歡，下次類似</button><button class="secondary" id="dislike">不太適合</button></div>')+'<div class="stop"><h3>接下來，照你的安排。</h3><p>需要搭車時，可以前往 yoxi 官網。本原型不會代叫車、帶入地址或完成訂單。</p><a class="secondary" id="next-move" href="https://www.yoxi.app/" target="_blank" rel="noopener noreferrer">前往 yoxi 官網 ↗</a></div><button class="primary" id="new-plan">下次有空，繼續帶路 →</button>');
 if($("#like"))$("#like").textContent="喜歡這次安排";
 const feedbackNote=document.createElement("p");feedbackNote.className="fine";feedbackNote.textContent="回饋只記錄在本機；下次沿用的是你選過的條件，尚未依店家回饋訓練排序。";$("#next-move").closest(".stop").before(feedbackNote);
 ["like","dislike"].forEach(v=>{if($("#"+v))$("#"+v).onclick=()=>{state.feedback=v;saveStore("yoxi.feedback",{value:v,choices:state.choices});track("recommendation_feedback",{value:v});renderFinished();};});$("#next-move").onclick=()=>track("next_move_clicked");$("#new-plan").onclick=()=>{state.stage=0;state.journey=null;state.route=null;state.places=[];state.excluded=[];state.error="";track("returned_user_opened");renderDiscover();updateMap();};}
async function initialiseMap(){try{const configController=new AbortController();const configTimer=setTimeout(()=>configController.abort(),10000);let config;try{config=await requestJson(API_BASE+"/api/config",{signal:configController.signal});}finally{clearTimeout(configTimer);}mapProvider=config.mapProvider||config.provider||"geoapify";const key=config.googleMapsBrowserKey||config.browserApiKey;if(!key)throw new Error("尚未設定瀏覽器地圖金鑰");
 if(mapProvider==="google"){await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error("Google 地圖載入逾時")),18000);window.yoxiMapReady=()=>{clearTimeout(timer);resolve();};window.gm_authFailure=()=>{clearTimeout(timer);mapFailure("Google 金鑰或網域限制未通過，請檢查設定。");reject(new Error("Google 地圖授權失敗"));};const script=document.createElement("script");script.src="https://maps.googleapis.com/maps/api/js?key="+encodeURIComponent(key)+"&callback=yoxiMapReady&loading=async&language=zh-TW&region=TW&v=weekly";script.onerror=()=>{clearTimeout(timer);reject(new Error("Google 地圖無法載入"));};document.head.appendChild(script);});map=new google.maps.Map($("#map"),{center:state.location||FALLBACK,zoom:15,disableDefaultUI:true,zoomControl:true,gestureHandling:"greedy",clickableIcons:false});mapReady=true;$("#map-badge").textContent="Google Maps";$("#map-message").hidden=true;updateMap();}
 else{map=new maplibregl.Map({container:"map",style:"https://maps.geoapify.com/v1/styles/positron/style.json?apiKey="+encodeURIComponent(key),center:[(state.location||FALLBACK).lng,(state.location||FALLBACK).lat],zoom:15,attributionControl:true});const mapTimer=setTimeout(()=>{if(!mapReady)mapFailure("地圖載入較久，請確認網路後重新整理。");},18000);map.on("load",()=>{clearTimeout(mapTimer);mapReady=true;$("#map-message").hidden=true;$("#map-badge").textContent="Geoapify 地圖・Google 尚未啟用";updateMap();});map.on("error",()=>{clearTimeout(mapTimer);mapFailure("地圖載入失敗，請檢查網路或金鑰網域限制。");});}}
 catch(error){mapFailure(error.name==="AbortError"?"讀取地圖設定逾時，請確認網路後重試。":error.message);}}
function mapFailure(message){$("#map-message").hidden=false;$("#map-message").textContent=message;$("#map-badge").textContent="地圖暫不可用";}
function routePoints(){const g=state.route?.geometry;return g?.type==="MultiLineString"?g.coordinates.flat():g?.type==="LineString"?g.coordinates:[];}
function updateMap(){if(!mapReady)return;markers.forEach(m=>mapProvider==="google"?m.setMap(null):m.remove());markers=[];lines.forEach(l=>l.setMap(null));lines=[];if(state.location){const all=[{location:{latitude:state.location.lat,longitude:state.location.lng},name:state.fallback?"大稻埕體驗起點":"出發點"},...state.places];all.forEach((p,i)=>{const pos={lat:p.location.latitude,lng:p.location.longitude};if(mapProvider==="google")markers.push(new google.maps.Marker({map,position:pos,title:p.name,label:i?String(i):"起"}));else markers.push(new maplibregl.Marker({color:i?"#f43d32":"#163143"}).setLngLat([pos.lng,pos.lat]).setPopup(new maplibregl.Popup().setText(p.name)).addTo(map));});}
 const points=routePoints();if(mapProvider==="google"){if(points.length)lines.push(new google.maps.Polyline({map,path:points.map(p=>({lat:p[1],lng:p[0]})),strokeColor:"#f43d32",strokeWeight:5,strokeOpacity:.9}));}else{if(map.getLayer("route"))map.removeLayer("route");if(map.getSource("route"))map.removeSource("route");if(points.length){map.addSource("route",{type:"geojson",data:state.route.geometry});map.addLayer({id:"route",type:"line",source:"route",paint:{"line-color":"#f43d32","line-width":5}});}}fitMap();}
function fitMap(){if(!mapReady)return;const points=routePoints();const expanded=$("#app").classList.contains("collapsed");const padding={top:expanded?95:20,bottom:25,left:30,right:30};if(points.length){if(mapProvider==="google"){const bounds=new google.maps.LatLngBounds();points.forEach(p=>bounds.extend({lat:p[1],lng:p[0]}));map.fitBounds(bounds,padding);}else{const bounds=new maplibregl.LngLatBounds();points.forEach(p=>bounds.extend(p));map.fitBounds(bounds,{padding,maxZoom:16});}}else if(state.location){if(mapProvider==="google"){map.setCenter(state.location);map.setZoom(15);}else map.flyTo({center:[state.location.lng,state.location.lat],zoom:15});}}
$("#sheet-toggle").onclick=()=>collapse(!$("#app").classList.contains("collapsed"));
let dragY=null,dragged=false;
$("#sheet-toggle").onpointerdown=e=>{dragY=e.clientY;dragged=false;e.currentTarget.setPointerCapture?.(e.pointerId);};
$("#sheet-toggle").onpointerup=e=>{if(dragY!==null&&Math.abs(e.clientY-dragY)>35){collapse(e.clientY>dragY);dragged=true;e.preventDefault();}dragY=null;if(e.currentTarget.hasPointerCapture?.(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);};
$("#sheet-toggle").onpointercancel=()=>{dragY=null;dragged=false;};
$("#sheet-toggle").addEventListener("click",e=>{if(dragged){e.stopImmediatePropagation();dragged=false;}},true);
$("#refresh-location").onclick=requestLocation;$("#settings-open").onclick=()=>$("#settings").showModal();$("#settings-close").onclick=()=>$("#settings").close();$("#clear-memory").onclick=()=>{try{["yoxi.preference","yoxi.events","yoxi.feedback"].forEach(k=>localStorage.removeItem(k));}catch{}toast("已清除本機偏好與操作紀錄。");if(state.screen==="discover")renderDiscover();};$("#export-events").onclick=()=>{const blob=new Blob([JSON.stringify(readStore("yoxi.events",[]),null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="yoxi-demo-events.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
setInterval(()=>{if(state.screen!=="journey"||!state.journey)return;const j=state.journey;const left=Math.max(0,state.minutes-Math.floor((Date.now()-j.startedAt)/60000));const status=$("#screen .status-line");if(status)status.textContent=(j.status==="returning"?"回程":(j.index+1)+" / "+state.places.length+" 站")+"・空檔還有約 "+left+" 分鐘";if(left===0&&!j.overtimeNotified){j.overtimeNotified=true;toast("時間預算已用完，請確認下一段安排；可以提早結束。");}},30000);
track("feature_opened");track("entry_nonride");if(readStore("yoxi.preference",null))track("returned_user_opened");renderDiscover();initialiseMap();requestLocation();
