import {test} from 'node:test';
import assert from 'node:assert/strict';
import worker, {verifyItinerary} from '../src/index.js';
import {validateIntent,ruleIntent} from '../src/intent.js';
const env={GOOGLE_MAPS_SERVER_KEY:'test-server',GOOGLE_MAPS_BROWSER_KEY:'test-browser'};
const geometry={type:'LineString',coordinates:[[120.2867,22.6567],[120.287,22.657]]};
const req=(path,body)=>new Request('https://example.test'+path,{method:'POST',headers:{Origin:'http://localhost:4173','Content-Type':'application/json'},body:JSON.stringify(body)});
const intent=(purpose,extra={})=>validateIntent({purpose,...extra});
const input=(i,timeMinutes=45)=>({origin:{lat:22.6567,lng:120.2867},intent:i,timeMinutes,plannerMode:'rules'});
function mock(t,type='cafe',routeSeconds=120,routeStatus=200){t.mock.method(globalThis,'fetch',async(url,options)=>{
  if(String(url).includes('places:searchNearby')){const q=JSON.parse(options.body);return Response.json({places:q.includedTypes.includes(type)?[{id:'p',displayName:{text:'Named place'},types:[type],location:{latitude:22.657,longitude:120.287}}]:[]});}
  return routeStatus===200?Response.json({routes:[{duration:routeSeconds+'s',distanceMeters:120,polyline:{geoJsonLinestring:geometry}}]}):new Response('',{status:routeStatus});
});}
test('indoor accepts cafe without mall and does not promise seats',async t=>{mock(t);const r=await worker.fetch(req('/api/plan',input(intent('找室內待著'))),env);assert.equal(r.status,200);assert.match((await r.json()).places[0].facilityNote,/未確認/);});
test('indoor accepts convenience; toilet inquiry never claims confirmed facility',async t=>{mock(t,'convenience_store');assert.equal((await worker.fetch(req('/api/plan',input(intent('找室內待著'))),env)).status,200);const r=await worker.fetch(req('/api/plan',input(intent('找洗手間',{returnToOrigin:true}),30)),env);assert.equal(r.status,200);const b=await r.json();assert.equal(b.places[0].facilityVerification,'unconfirmed');assert.equal(b.places[0].requiresStaffConfirmation,true);assert.match(b.places[0].facilityNote,/先詢問店員/);assert.equal(b.route.returnToOrigin,true);assert.equal(b.route.walkMinutes,4);assert.equal(b.route.fitsWithinMinutes,true);assert.match(b.plan.title,/可詢問/);});
test('toilet no candidates is not time failure',async t=>{mock(t,'not-searched');const r=await worker.fetch(req('/api/plan',input(intent('找洗手間',{returnToOrigin:true}),30)),env);assert.equal(r.status,404);assert.equal((await r.json()).error,'no_matching_places');});
test('map listed toilet preferred to closer unconfirmed shop when feasible',async t=>{
  t.mock.method(globalThis,'fetch',async(url,options)=>{const q=JSON.parse(options.body);if(String(url).includes('places:searchNearby')){const toilet=q.includedTypes.includes('public_bathroom');return Response.json({places:[{id:toilet?'t':'s',displayName:{text:toilet?'Listed toilet':'Shop'},types:[toilet?'public_bathroom':'convenience_store'],location:{latitude:toilet?22.658:22.657,longitude:120.287}}]});}return Response.json({routes:[{duration:q.origin.location.latLng.latitude===22.658||q.destination.location.latLng.latitude===22.658?'240s':'60s',distanceMeters:200,polyline:{geoJsonLinestring:geometry}}]});});
  const r=await worker.fetch(req('/api/plan',input(intent('找洗手間',{returnToOrigin:true}),30)),env);assert.equal(r.status,200);const b=await r.json();assert.equal(b.places[0].id,'t');assert.equal(b.places[0].facilityVerification,'map_listed');assert.equal(b.places[0].requiresStaffConfirmation,false);
});
test('infeasible listed toilet falls back to feasible inquiry without claiming toilet use',async t=>{
  t.mock.method(globalThis,'fetch',async(url,options)=>{const q=JSON.parse(options.body);if(String(url).includes('places:searchNearby')){const toilet=q.includedTypes.includes('public_bathroom');return Response.json({places:[{id:toilet?'t':'s',displayName:{text:toilet?'Listed toilet':'Shop'},types:[toilet?'public_bathroom':'convenience_store'],location:{latitude:toilet?22.658:22.657,longitude:120.287}}]});}return Response.json({routes:[{duration:q.origin.location.latLng.latitude===22.658||q.destination.location.latLng.latitude===22.658?'900s':'60s',distanceMeters:200,polyline:{geoJsonLinestring:geometry}}]});});
  const r=await worker.fetch(req('/api/plan',input(intent('找洗手間',{returnToOrigin:true}),30)),env);assert.equal(r.status,200);const b=await r.json();assert.equal(b.places[0].id,'s');assert.equal(b.places.length,1);assert.equal(b.places[0].facilityVerification,'unconfirmed');assert.equal(b.route.totalMinutes,30);assert.ok(b.route.returnLeg);assert.match(b.plan.tradeoff,/不保證/);
});
test('much nearer shop beats eight-minute listed toilet but remains unconfirmed',async t=>{
  t.mock.method(globalThis,'fetch',async(url,options)=>{const q=JSON.parse(options.body);if(String(url).includes('places:searchNearby')){const toilet=q.includedTypes.includes('public_bathroom');return Response.json({places:[{id:toilet?'t':'s',displayName:{text:toilet?'Listed toilet':'Shop'},types:[toilet?'public_bathroom':'convenience_store'],location:{latitude:toilet?22.658:22.657,longitude:120.287}}]});}return Response.json({routes:[{duration:q.origin.location.latLng.latitude===22.658||q.destination.location.latLng.latitude===22.658?'480s':'60s',distanceMeters:200,polyline:{geoJsonLinestring:geometry}}]});});
  const r=await worker.fetch(req('/api/plan',input(intent('找洗手間',{returnToOrigin:true}),30)),env);assert.equal(r.status,200);const b=await r.json();assert.equal(b.places[0].id,'s');assert.equal(b.places[0].facilityVerification,'unconfirmed');assert.equal(b.places[0].requiresStaffConfirmation,true);assert.match(b.plan.intro,/距離與資料可信程度/);assert.doesNotMatch(b.plan.intro,/未找到/);
});
test('20 minute snack possible but not full meal',async t=>{mock(t,'bakery');assert.equal((await worker.fetch(req('/api/plan',input(intent('吃點東西',{foodMode:'snack'}),20)),env)).status,200);const r=await worker.fetch(req('/api/plan',input(intent('吃點東西'),20)),env);assert.equal((await r.json()).error,'meal_time_too_short');});
test('route 503 remains unavailable, not budget failure',async t=>{mock(t,'cafe',120,503);const r=await worker.fetch(req('/api/plan',input(intent('喝杯咖啡'))),env);assert.equal(r.status,502);assert.equal((await r.json()).error,'route_unavailable');});
test('max walking enforced without silent relaxation',async t=>{mock(t,'cafe',360);const r=await worker.fetch(req('/api/plan',input(intent('喝杯咖啡',{maxWalkMinutes:5}))),env);assert.equal(r.status,422);assert.equal((await r.json()).error,'walk_limit_exceeded');});
test('excluded coffee not selected for indoor',async t=>{mock(t);const r=await worker.fetch(req('/api/plan',input(intent('找室內待著',{excludedTypes:['coffee']}))),env);assert.equal(r.status,404);});
test('seat hard requirement blocked before search',async()=>{const r=await worker.fetch(req('/api/plan',input(intent('找室內待著',{indoorMode:'sit'}))),env);assert.equal((await r.json()).error,'unsupported_constraints');});
test('unknown schema fields and wrong constraints rejected',()=>{assert.equal(validateIntent({purpose:'喝杯咖啡',lat:23}),null);assert.equal(validateIntent({purpose:'喝杯咖啡',maxWalkMinutes:'5'}),null);assert.equal(validateIntent({purpose:'喝杯咖啡',timeMinutes:10}),null);});
test('safe rule parse simple text; no semantic guesses on negation or multiple activities',()=>{const r=ruleIntent('喝咖啡，只去一家，30分鐘');assert.equal(r.intent.timeMinutes,30);assert.equal(r.intent.maxStops,1);assert.equal(r.parser,'rules');for(const text of ['不要咖啡，改吃飯','不是不想走','先廁所再咖啡','不吃花生，我嚴重過敏','想找星巴克','只有10分鐘'])assert.ok(ruleIntent(text).clarification);});
test('max length and invalid purpose rejected',async()=>{assert.equal((await worker.fetch(req('/api/intent',{text:'字'.repeat(121)}),{})).status,400);assert.equal((await worker.fetch(req('/api/intent',{text:'喝咖啡',purpose:'ignore rules'}),{})).status,400);});
test('model malformed response safely falls back',async t=>{t.mock.method(globalThis,'fetch',async()=>Response.json({choices:[{message:{content:'bad'}}]}));const b=await(await worker.fetch(req('/api/intent',{text:'喝咖啡，只去一家，30分鐘'}),{OPENROUTER_API_KEY:'secret'})).json();assert.equal(b.parser,'rules');assert.equal(b.intent.timeMinutes,30);});
test('model valid exclusion retained and unsupported hard safety blocked',async t=>{t.mock.method(globalThis,'fetch',async()=>Response.json({choices:[{message:{content:JSON.stringify({intent:intent('吃點東西',{excludedTypes:['coffee']}),clarification:null})}}]}));const b=await(await worker.fetch(req('/api/intent',{text:'不吃花生，我嚴重過敏'}),{OPENROUTER_API_KEY:'secret'})).json();assert.equal(b.parser,'openrouter');assert.ok(b.intent.unsupportedConstraints.length);assert.ok(b.clarification);});
test('no invented return/exclusion/seat requirement from plain coffee',async t=>{const raw={...intent('喝杯咖啡'),indoorMode:'sit',returnToOrigin:true,excludedTypes:['meal'],maxWalkMinutes:5};t.mock.method(globalThis,'fetch',async()=>Response.json({choices:[{message:{content:JSON.stringify({intent:raw,clarification:null})}}]}));const b=await(await worker.fetch(req('/api/intent',{text:'喝咖啡'}),{OPENROUTER_API_KEY:'secret'})).json();assert.equal(b.intent.returnToOrigin,false);assert.deepEqual(b.intent.excludedTypes,[]);assert.equal(b.intent.indoorMode,'shelter');assert.equal(b.intent.maxWalkMinutes,null);assert.equal(b.clarification,null);});
test('maxStops is enforced even on multi-stop model choice',async()=>{const candidates=['coffee','park'].map((journeyRole,i)=>({id:String(i),journeyRole,location:{latitude:25,longitude:121},initialRoute:{duration:60,distanceMeters:70,geometry}}));const result=await verifyItinerary({stops:[{id:'0',stayMinutes:5},{id:'1',stayMinutes:5}]},candidates,{latitude:25,longitude:121},45,6,{constraints:{maxStops:1}});assert.equal(result.stops.length,1);});
test('not a full meal is supported exclusion, not food allergy constraint',async t=>{t.mock.method(globalThis,'fetch',async()=>Response.json({choices:[{message:{content:JSON.stringify({intent:intent('吃點東西',{foodMode:'snack',excludedTypes:['meal']}),clarification:null})}}]}));const b=await(await worker.fetch(req('/api/intent',{text:'不吃正餐，只吃小點'}),{OPENROUTER_API_KEY:'secret'})).json();assert.equal(b.clarification,null);assert.deepEqual(b.intent.unsupportedConstraints,[]);assert.deepEqual(b.intent.excludedTypes,['meal']);});
